version: '3'
services:
  php:
    build:
      context: app
      target: builder
    networks:
      - apache_network
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    networks:
      - apache_network
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
volumes:
  mysql_data:


networks:
  apache_network:
    driver: bridge
